// Generated by scripts/make_chip_sprites.py, do not edit.
#ifndef CHIP_PALETTES_H
#define CHIP_PALETTES_H

#include "bn_color.h"
#include "bn_bpp_mode.h"
#include "bn_sprite_palette_item.h"

namespace Game
{
    // The chips and chip_stack sprites are drawn once and recolored with these.
    // Indexes 0..5 are the bet values 1, 2, 4, 8, 16 and 32.
    //     white, red, blue, green, black, purple, pink, yellow
    constexpr int chip_palette_count = 8;

    inline constexpr bn::color chip_palette_colors[chip_palette_count][16] = {
        { bn::color(0, 31, 0), bn::color(2, 1, 3), bn::color(2, 4, 7), bn::color(2, 4, 7), bn::color(2, 4, 7), bn::color(4, 7, 11), bn::color(21, 22, 22), bn::color(24, 25, 25), bn::color(29, 29, 29), bn::color(29, 29, 29), bn::color(16, 18, 18), bn::color(21, 22, 22), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0) },
        { bn::color(0, 31, 0), bn::color(2, 1, 3), bn::color(8, 3, 6), bn::color(20, 6, 6), bn::color(21, 22, 22), bn::color(29, 29, 29), bn::color(8, 3, 6), bn::color(14, 4, 7), bn::color(20, 6, 6), bn::color(20, 6, 6), bn::color(8, 3, 6), bn::color(14, 4, 7), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0) },
        { bn::color(0, 31, 0), bn::color(2, 1, 3), bn::color(7, 11, 17), bn::color(14, 23, 26), bn::color(21, 22, 22), bn::color(29, 29, 29), bn::color(7, 11, 17), bn::color(9, 17, 23), bn::color(14, 23, 26), bn::color(14, 23, 26), bn::color(7, 11, 17), bn::color(9, 17, 23), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0) },
        { bn::color(0, 31, 0), bn::color(2, 1, 3), bn::color(3, 6, 5), bn::color(3, 6, 5), bn::color(21, 22, 22), bn::color(29, 29, 29), bn::color(3, 6, 5), bn::color(4, 10, 5), bn::color(8, 16, 6), bn::color(8, 16, 6), bn::color(3, 6, 5), bn::color(4, 10, 5), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0) },
        { bn::color(0, 31, 0), bn::color(2, 1, 3), bn::color(4, 5, 6), bn::color(4, 5, 6), bn::color(21, 22, 22), bn::color(29, 29, 29), bn::color(4, 5, 6), bn::color(2, 2, 3), bn::color(2, 2, 3), bn::color(4, 5, 6), bn::color(4, 5, 6), bn::color(2, 2, 3), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0) },
        { bn::color(0, 31, 0), bn::color(2, 1, 3), bn::color(8, 4, 10), bn::color(20, 7, 17), bn::color(21, 22, 22), bn::color(29, 29, 29), bn::color(8, 4, 10), bn::color(15, 6, 15), bn::color(20, 7, 17), bn::color(20, 7, 17), bn::color(8, 4, 10), bn::color(15, 6, 15), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0) },
        { bn::color(0, 31, 0), bn::color(2, 1, 3), bn::color(20, 7, 17), bn::color(27, 16, 20), bn::color(21, 22, 22), bn::color(29, 29, 29), bn::color(20, 7, 17), bn::color(24, 10, 18), bn::color(27, 16, 20), bn::color(27, 16, 20), bn::color(20, 7, 17), bn::color(24, 10, 18), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0) },
        { bn::color(0, 31, 0), bn::color(2, 1, 3), bn::color(23, 14, 5), bn::color(29, 24, 14), bn::color(21, 22, 22), bn::color(29, 29, 29), bn::color(23, 14, 5), bn::color(27, 19, 8), bn::color(29, 24, 14), bn::color(29, 24, 14), bn::color(23, 14, 5), bn::color(27, 19, 8), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0), bn::color(0, 0, 0) },
    };

    [[nodiscard]] constexpr bn::sprite_palette_item chip_palette_item(int index)
    {
        return bn::sprite_palette_item(chip_palette_colors[index], bn::bpp_mode::BPP_4);
    }
}

#endif // CHIP_PALETTES_H
