// Generated by scripts/make_sprite_font.py from madspixel.ttf. Do not edit by hand.

#ifndef MADSPIXEL_SPRITE_FONT_H
#define MADSPIXEL_SPRITE_FONT_H

#include "bn_sprite_font.h"
#include "bn_utf8_characters_map.h"
#include "bn_sprite_items_madspixel_font.h"

namespace Game
{
    constexpr bn::utf8_character madspixel_sprite_font_utf8_characters[] = {
        "Á", "É", "Í", "Ó", "Ú", "Ü", "Ñ", "á", "é", "í", "ó", "ú", "ü", "ñ", "¡", "¿"
    };

    constexpr int8_t madspixel_sprite_font_character_widths[] = {
        5,  // 32
        3,  // 33 !
        7,  // 34 "
        12,  // 35 #
        9,  // 36 $
        13,  // 37 %
        12,  // 38 &
        5,  // 39 '
        6,  // 40 (
        6,  // 41 )
        7,  // 42 *
        9,  // 43 +
        5,  // 44 ,
        7,  // 45 -
        5,  // 46 .
        6,  // 47 /
        9,  // 48 0
        9,  // 49 1
        8,  // 50 2
        9,  // 51 3
        9,  // 52 4
        9,  // 53 5
        8,  // 54 6
        9,  // 55 7
        10,  // 56 8
        8,  // 57 9
        5,  // 58 :
        5,  // 59 ;
        10,  // 60 <
        10,  // 61 =
        10,  // 62 >
        9,  // 63 ?
        15,  // 64 @
        10,  // 65 A
        10,  // 66 B
        11,  // 67 C
        11,  // 68 D
        10,  // 69 E
        10,  // 70 F
        13,  // 71 G
        12,  // 72 H
        7,  // 73 I
        9,  // 74 J
        10,  // 75 K
        9,  // 76 L
        15,  // 77 M
        12,  // 78 N
        12,  // 79 O
        10,  // 80 P
        14,  // 81 Q
        11,  // 82 R
        9,  // 83 S
        11,  // 84 T
        11,  // 85 U
        11,  // 86 V
        14,  // 87 W
        10,  // 88 X
        9,  // 89 Y
        10,  // 90 Z
        5,  // 91 [
        6,  // 92
        5,  // 93 ]
        9,  // 94 ^
        11,  // 95 _
        6,  // 96 `
        8,  // 97 a
        10,  // 98 b
        8,  // 99 c
        10,  // 100 d
        9,  // 101 e
        7,  // 102 f
        9,  // 103 g
        9,  // 104 h
        5,  // 105 i
        5,  // 106 j
        10,  // 107 k
        5,  // 108 l
        14,  // 109 m
        10,  // 110 n
        9,  // 111 o
        10,  // 112 p
        10,  // 113 q
        7,  // 114 r
        7,  // 115 s
        5,  // 116 t
        9,  // 117 u
        8,  // 118 v
        10,  // 119 w
        11,  // 120 x
        9,  // 121 y
        8,  // 122 z
        7,  // 123 {
        4,  // 124 |
        7,  // 125 }
        11,  // 126 ~
        10,  // Á
        10,  // É
        7,  // Í
        12,  // Ó
        11,  // Ú
        11,  // Ü
        12,  // Ñ
        8,  // á
        9,  // é
        5,  // í
        9,  // ó
        9,  // ú
        9,  // ü
        10,  // ñ
        5,  // ¡
        9,  // ¿
    };

    constexpr bn::span<const bn::utf8_character> madspixel_sprite_font_utf8_characters_span(
            madspixel_sprite_font_utf8_characters);

    constexpr auto madspixel_sprite_font_utf8_characters_map =
            bn::utf8_characters_map<madspixel_sprite_font_utf8_characters_span>();

    constexpr bn::sprite_font madspixel_sprite_font(
            bn::sprite_items::madspixel_font, madspixel_sprite_font_utf8_characters_map.reference(),
            madspixel_sprite_font_character_widths);
}

#endif // MADSPIXEL_SPRITE_FONT_H
